apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-deployment
  labels:
    app: {{ .Values.appName }}
spec:
  {{- if not .Values.hpa.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      {{- if .Values.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      {{- end }}
      containers:
        - name: {{ .Values.appName }}-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.containerPort }}
          {{- if or .Values.envFromSecrets .Values.envFromConfigMaps }}
          envFrom:
            {{- range .Values.envFromConfigMaps }}
            - configMapRef:
                name: {{ . }}
            {{- end }}
            {{- range .Values.envFromSecrets }}
            - secretRef:
                name: {{ . }}
                optional: true
            {{- end }}
          {{- end }}
          {{- if .Values.env }}
          env:
            {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          {{- end }}
          {{- if .Values.fileSecrets }}
          volumeMounts:
            {{- range .Values.fileSecrets }}
            - name: {{ .name }}-vol
              mountPath: {{ .mountPath }}
              {{- if .subPath }}
              subPath: {{ .subPath }}
              {{- end }}
              readOnly: true
            {{- end }}
          {{- end }}
          {{- if .Values.probes.enabled }}
          readinessProbe:
            httpGet: { path: {{ .Values.probes.path }}, port: {{ .Values.containerPort }} }
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: {{ .Values.probes.path }}, port: {{ .Values.containerPort }} }
            initialDelaySeconds: 30
            periodSeconds: 15
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.fileSecrets }}
      volumes:
        {{- range .Values.fileSecrets }}
        - name: {{ .name }}-vol
          secret:
            secretName: {{ .name }}
        {{- end }}
      {{- end }}
