apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-service
  labels:
    app: {{ .Values.appLabel }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.appLabel }}
  ports:
    - name: app-port
      port: {{ .Values.servicePort }}
      targetPort: app-port
      protocol: TCP
